-- QR Destekli Stok ve Barkod Yönetimi — PostgreSQL tablo şeması
-- Çalıştırma: psql -U KULLANICI -d StokVeBarkodYonetimiDB -f 01_create_tables.sql
-- Not: Tüm tablo ve kolon adları uygulama kodundaki (Dapper) PascalCase isimlerle eşleşir.

BEGIN;

-- ── KullaniciTip ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "KullaniciTip" (
    "ID"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Ad"          VARCHAR(100) NOT NULL,
    "Aktif"       BOOLEAN NOT NULL DEFAULT TRUE,
    "Varsayilan"  BOOLEAN NOT NULL DEFAULT FALSE,
    "CreUser"     INTEGER NOT NULL DEFAULT 0,
    "CreDate"     TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdUser"     INTEGER,
    "UpdDate"     TIMESTAMP,
    "DelUser"     INTEGER,
    "DelDate"     TIMESTAMP
);

-- ── Kullanicilar ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Kullanicilar" (
    "ID"              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "KullaniciTip_ID" INTEGER NOT NULL REFERENCES "KullaniciTip" ("ID"),
    "Ad"              VARCHAR(100) NOT NULL,
    "Soyad"           VARCHAR(100) NOT NULL,
    "Eposta"          VARCHAR(200) NOT NULL,
    "Sifre"           VARCHAR(500) NOT NULL,
    "ProfilResmi"     VARCHAR(500),
    "Aktif"           BOOLEAN NOT NULL DEFAULT TRUE,
    "CreUser"         INTEGER NOT NULL DEFAULT 0,
    "CreDate"         TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdUser"         INTEGER,
    "UpdDate"         TIMESTAMP,
    "DelUser"         INTEGER,
    "DelDate"         TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "IX_Kullanicilar_Eposta"
    ON "Kullanicilar" (LOWER("Eposta"))
    WHERE "DelUser" IS NULL;

-- ── Form (menü / sayfa RBAC) ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Form" (
    "ID"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Ad"          VARCHAR(150) NOT NULL,
    "IsMenu"      BOOLEAN NOT NULL DEFAULT TRUE,
    "UstMenu_ID"  INTEGER REFERENCES "Form" ("ID"),
    "Sira"        INTEGER NOT NULL DEFAULT 0,
    "SayfaURL"    VARCHAR(200),
    "Icon"        VARCHAR(100),
    "CreUser"     INTEGER NOT NULL DEFAULT 0,
    "CreDate"     TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdUser"     INTEGER,
    "UpdDate"     TIMESTAMP,
    "DelUser"     INTEGER,
    "DelDate"     TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "IX_Form_SayfaURL"
    ON "Form" (LOWER("SayfaURL"))
    WHERE "DelUser" IS NULL AND "SayfaURL" IS NOT NULL;

-- ── KullaniciDetay (kullanıcıya özel form yetkisi) ───────────────────────────
CREATE TABLE IF NOT EXISTS "KullaniciDetay" (
    "ID"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Kullanici_ID" INTEGER NOT NULL REFERENCES "Kullanicilar" ("ID"),
    "Form_ID"      INTEGER NOT NULL REFERENCES "Form" ("ID"),
    "Yetki"        INTEGER NOT NULL DEFAULT 0,
    "CreUser"      INTEGER NOT NULL DEFAULT 0,
    "CreDate"      TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdUser"      INTEGER,
    "UpdDate"      TIMESTAMP,
    "DelUser"      INTEGER,
    "DelDate"      TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_KullaniciDetay_Aktif"
    ON "KullaniciDetay" ("Kullanici_ID", "Form_ID")
    WHERE "DelUser" IS NULL;

-- ── KullaniciTipDetay (role form yetkisi) ────────────────────────────────────
CREATE TABLE IF NOT EXISTS "KullaniciTipDetay" (
    "ID"              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "KullaniciTip_ID" INTEGER NOT NULL REFERENCES "KullaniciTip" ("ID"),
    "Form_ID"         INTEGER NOT NULL REFERENCES "Form" ("ID"),
    "Yetki"           INTEGER NOT NULL DEFAULT 0,
    "CreUser"         INTEGER NOT NULL DEFAULT 0,
    "CreDate"         TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdUser"         INTEGER,
    "UpdDate"         TIMESTAMP,
    "DelUser"         INTEGER,
    "DelDate"         TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_KullaniciTipDetay_Aktif"
    ON "KullaniciTipDetay" ("KullaniciTip_ID", "Form_ID")
    WHERE "DelUser" IS NULL;

-- ── Birim ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Birim" (
    "ID"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Ad"      VARCHAR(50) NOT NULL,
    "Aktif"   BOOLEAN NOT NULL DEFAULT TRUE,
    "CreUser" INTEGER NOT NULL DEFAULT 0,
    "CreDate" TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdUser" INTEGER,
    "UpdDate" TIMESTAMP,
    "DelUser" INTEGER,
    "DelDate" TIMESTAMP
);

-- ── Kategoriler ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Kategoriler" (
    "ID"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ResimYolu" VARCHAR(500),
    "Ad"        VARCHAR(150) NOT NULL,
    "Aciklama"  VARCHAR(500),
    "Aktif"     BOOLEAN NOT NULL DEFAULT TRUE,
    "CreUser"   INTEGER NOT NULL DEFAULT 0,
    "CreDate"   TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdUser"   INTEGER,
    "UpdDate"   TIMESTAMP,
    "DelUser"   INTEGER,
    "DelDate"   TIMESTAMP
);

-- ── Urunler ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Urunler" (
    "ID"                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UrunKodu"           VARCHAR(50) NOT NULL,
    "Kategori_ID"        INTEGER NOT NULL REFERENCES "Kategoriler" ("ID"),
    "BarkodNo"           VARCHAR(20),
    "ResimYolu"          VARCHAR(500),
    "Ad"                 VARCHAR(150) NOT NULL,
    "Aciklama"           VARCHAR(250),
    "Birim_ID"           INTEGER NOT NULL REFERENCES "Birim" ("ID"),
    "Stok"               INTEGER NOT NULL DEFAULT 0,
    "KritikStokSeviyesi" INTEGER NOT NULL DEFAULT 0,
    "CreUser"            INTEGER NOT NULL DEFAULT 0,
    "CreDate"            TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdUser"            INTEGER,
    "UpdDate"            TIMESTAMP,
    "DelUser"            INTEGER,
    "DelDate"            TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "IX_Urunler_BarkodNo"
    ON "Urunler" ("BarkodNo")
    WHERE "DelUser" IS NULL AND "BarkodNo" IS NOT NULL;

-- ── StokHareketleri ──────────────────────────────────────────────────────────
-- HareketTipi: 1 = Giriş, 2 = Çıkış
CREATE TABLE IF NOT EXISTS "StokHareketleri" (
    "ID"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Urun_ID"     INTEGER NOT NULL REFERENCES "Urunler" ("ID"),
    "HareketTipi" SMALLINT NOT NULL,
    "Miktar"      NUMERIC(18, 2) NOT NULL,
    "Not"         VARCHAR(500),
    "CreUser"     INTEGER NOT NULL DEFAULT 0,
    "CreDate"     TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdUser"     INTEGER,
    "UpdDate"     TIMESTAMP,
    "DelUser"     INTEGER,
    "DelDate"     TIMESTAMP,
    CONSTRAINT "CK_StokHareketleri_HareketTipi" CHECK ("HareketTipi" IN (1, 2)),
    CONSTRAINT "CK_StokHareketleri_Miktar" CHECK ("Miktar" > 0)
);

CREATE INDEX IF NOT EXISTS "IX_StokHareketleri_Urun_ID"
    ON "StokHareketleri" ("Urun_ID")
    WHERE "DelUser" IS NULL;

COMMIT;
